language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv /ssl/fullchain.pem /ssl/fullchain.pem
  - mv /ssl/privkey.pem /ssl/privkey.pem
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
