homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml
  #packages: !include_dir_named packages

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

cloud:

map:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml

# View all events in a logbook
logbook: !include logbook.yaml

recorder: !include recorder.yaml

# Track the sun
sun:

# Text to speech
tts:
  platform: google

zwave:
  usb_path: /dev/ttyACM0

ifttt:
  key: !secret ifttt_key

ecobee:
  api_key: !secret ecobee_api_key

hue:
  bridges:
    - host: 192.168.0.2

android_ip_webcam:
  - host: 192.168.0.6
    name: Garage
    scan_interval: 5

alert: !include alerts.yaml
automation: !include automations.yaml
camera: !include cameras.yaml
cover: !include cover.yaml
device_tracker: !include device_trackers.yaml
group: !include groups.yaml
history_graph: !include graphs.yaml
notify: !include notify.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
panel_iframe: !include iframes.yaml
zone: !include zones.yaml
