homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

cloud:

map:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml

# View all events in a logbook
logbook: !include logbook.yaml

recorder: !include recorder.yaml

# Track the sun
sun:

# Text to speech
tts:
  platform: google

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url

cover:
  - platform: template
    covers:
      garagedoor:
        friendly_name: "Garage Door"
        open_cover:
          service: script.garagedoor
          data:
            modus: 'open'
        close_cover:
          service: script.garagedoor
          data:
            modus: 'close'
        # stop_cover:
        #   service: script.garagedoor
        #   data:
        #     modus: 'stop'
        value_template: "{{is_state('sensor.garagedoor', 'open')}}"
        icon_template: >-
          {% if is_state('sensor.garagedoor', 'open') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}

zwave:
  usb_path: /dev/ttyACM0

ifttt:
  key: !secret ifttt_key

ecobee:
  api_key: !secret ecobee_api_key

hue:
  bridges:
    - host: 192.168.0.2

android_ip_webcam:
  - host: 192.168.0.5
    name: Living Room
    scan_interval: 5

camera:
- platform: generic
  name: Weather Radar
  content_type: image/gif
  still_image_url: http://cdn.tegna-media.com/wfaa/weather/animated-loops/comp/880x495/new_dma.gif
    #https://radar.weather.gov/ridge/lite/N0R/FWS_loop.gif

notify: !include notify.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
group: !include groups.yaml
automation: !include automations.yaml
history_graph: !include graphs.yaml
device_tracker: !include device_trackers.yaml
