- platform: template
  covers:
    garagedoor:
      friendly_name: "Garage Door"
      open_cover:
        service: script.garagedoor
        data:
          modus: 'open'
      close_cover:
        service: script.garagedoor
        data:
          modus: 'close'
      stop_cover:
        service: script.garagedoor
        data:
          modus: 'stop'
      value_template: "{{is_state('binary_sensor.garage_door', 'on')}}"
      icon_template: >-
        {% if is_state('binary_sensor.garage_door', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}