- platform: owntracks_http
- platform: bluetooth_tracker
- platform: ping
  hosts:
    amplifi: 192.168.0.1
    nicks_phone: 192.168.0.12
    alberts_phone: 192.168.0.13
    elenas_phone: 192.168.0.14
    ikonixx: 192.168.0.50
