- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - temperature
    - apparent_temperature
    - temperature_max
    - temperature_min
    - humidity
    - wind_speed
    - wind_bearing

- platform: pollen
  zip_code: !secret zip_code
  monitored_conditions:
    - allergy_average_forecasted
    - allergy_index_today
    - allergy_index_tomorrow

- platform: template
  sensors:
    wind_dir:
      friendly_name: 'Wind Direction'
      value_template: >-
       {% set wind_dir = states.sensor.dark_sky_wind_bearing.state %}
       {% if wind_dir | float<=23 %}North
       {% elif wind_dir | float>338 %}North
       {% elif 23 < (wind_dir|float) <=68 %}Northeast
       {% elif 68 < (wind_dir|float) <=113 %}East
       {% elif 113 < (wind_dir|float) <=158 %}Southeast
       {% elif 158 < (wind_dir|float) <=203 %}South
       {% elif 203 < (wind_dir|float) <=248 %}Southwest
       {% elif 248 < (wind_dir|float) <=293 %}West
       {% elif 293 < (wind_dir|float) <=338 %}Northwest
       {%- endif %}

- platform: template
  sensors:
    forecasted_allergy_index:
      friendly_name: 'Forecasted Allergy Index'
      value_template: >
        {% if states.sensor.allergy_index_forecasted_average.state|float <= 2.4 %}Low
        {% elif states.sensor.allergy_index_forecasted_average.state|float <= 4.8 %}Low-Medium
        {% elif states.sensor.allergy_index_forecasted_average.state|float <= 7.2 %}Medium
        {% elif states.sensor.allergy_index_forecasted_average.state|float <= 9.6 %}Medium-High
        {% elif states.sensor.allergy_index_forecasted_average.state|float <= 12.0 %}High
        {% else %}Unknown
        {% endif %}

- platform: template
  sensors:
    allergy_index_today:
      friendly_name: 'Allergy Index Today'
      value_template: >
        {% if states.sensor.allergy_index_today_2.state|float <= 2.4 %}Low
        {% elif states.sensor.allergy_index_today_2.state|float <= 4.8 %}Low-Medium
        {% elif states.sensor.allergy_index_today_2.state|float <= 7.2 %}Medium
        {% elif states.sensor.allergy_index_today_2.state|float <= 9.6 %}Medium-High
        {% elif states.sensor.allergy_index_today_2.state|float <= 12.0 %}High
        {% else %}Unknown
        {% endif %}

- platform: template
  sensors:
    allergy_index_tomorrow:
      friendly_name: 'Allergy Index Tomorrow'
      value_template: >
        {% if states.sensor.allergy_index_tomorrow_2.state|float <= 2.4 %}Low
        {% elif states.sensor.allergy_index_tomorrow_2.state|float <= 4.8 %}Low-Medium
        {% elif states.sensor.allergy_index_tomorrow_2.state|float <= 7.2 %}Medium
        {% elif states.sensor.allergy_index_tomorrow_2.state|float <= 9.6 %}Medium-High
        {% elif states.sensor.allergy_index_tomorrow_2.state|float <= 12.0 %}High
        {% else %}Unknown
        {% endif %}

- platform: template
  sensors:
    battery_brian_v30:
      value_template: '{{ states.device_tracker.brian_v30.attributes.battery|default(0)|int() }}'
      unit_of_measurement: "%"
      icon_template: >
        {% set battery_level = states.device_tracker.brian_v30.attributes.battery|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

- platform: template
  sensors:
    battery_jennifer_stylo3plus:
      value_template: '{{ states.device_tracker.jennifer_stylo3plus.attributes.battery|default(0)|int() }}'
      unit_of_measurement: "%"
      icon_template: >
        {% set battery_level = states.device_tracker.jennifer_stylo3plus.attributes.battery|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}

- platform: template
  sensors:
    garage_door_battery:
      value_template: >-
        {%- if states.zwave.vision_zg8101_garage_door_detector -%}
          {{ states.zwave.vision_zg8101_garage_door_detector.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.vision_zg8101_garage_door_detector

- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: since_last_boot

- platform: speedtest
  server_id: 13682
  minute:
    - 0
    - 30
  monitored_conditions:
    - download
    - upload
    - ping

- platform: template
  sensors:
    since_last_boot_templated:
      value_template: >-
        {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
        {%- set count = slb | length -%}
        {%- set hms = slb[count - 1] -%}
        {%- set hms_trimmed = hms.split('.')[0] -%}
        {%- set hms_split = hms_trimmed.split(':') -%}
        {%- set hours = hms_split[0] | int -%}

        {%- if count == 3 -%}
          {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 hour
          {%- else -%}
            {{ hours }} hours
          {%- endif -%}
        {%- endif -%}

- platform: rest
  resource: https://api.ipify.org/?format=json
  name: External IP
  value_template: '{{ value_json.ip }}'

- platform: google_travel_time
  api_key: !secret google_travel_time_api_key
  name: Brian - Home
  origin: device_tracker.brian_v30
  destination: !secret home

# - platform: google_travel_time
#   api_key: !secret google_travel_time_api_key
#   name: Brian - Work
#   origin: device_tracker.brian_v30
#   destination: !secret brian_work

- platform: google_travel_time
  api_key: !secret google_travel_time_api_key
  name: Jennifer - Home
  origin: device_tracker.jennifer_stylo3plus
  destination: !secret home

# - platform: google_travel_time
#   api_key: !secret google_travel_time_api_key
#   name: Jennifer - Work
#   origin: device_tracker.jennifer_stylo3plus
#   destination: !secret jennifer_work

- platform: template
  sensors:
    amplifi:
      value_template: "{% if is_state('device_tracker.amplifi', 'home') %}Online{% else %}Offline{% endif %}"

- platform: template
  sensors:
    ikonixx:
      value_template: "{% if is_state('device_tracker.ikonixx', 'home') %}Online{% else %}Offline{% endif %}"

- platform: template
  sensors:
    brians_phone:
      value_template: "{% if is_state('device_tracker.brians_phone', 'home') %}Online{% else %}Offline{% endif %}"

- platform: template
  sensors:
    jennifers_phone:
      value_template: "{% if is_state('device_tracker.jennifers_phone', 'home') %}Online{% else %}Offline{% endif %}"

- platform: template
  sensors:
    nicks_phone:
      value_template: "{% if is_state('device_tracker.nicks_phone', 'home') %}Online{% else %}Offline{% endif %}"

- platform: template
  sensors:
    alberts_phone:
      value_template: "{% if is_state('device_tracker.alberts_phone', 'home') %}Online{% else %}Offline{% endif %}"

- platform: template
  sensors:
    elenas_phone:
      value_template: "{% if is_state('device_tracker.elenas_phone', 'home') %}Online{% else %}Offline{% endif %}"

- platform: version
  name: HASS Current Version

- platform: cert_expiry
  host: !secret cert_expiry_host
